name = "telegramshop"
main = "src/worker.js"
compatibility_date = "2026-01-01"

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "b3185c5a-8143-4181-9030-8c29af6c2bc7"

[[kv_namespaces]]
binding = "STATE"
id = "53d33d98dc004d14aae6684fc56db119"
preview_id = "53d33d98dc004d14aae6684fc56db119"